### PR TITLE
Fix issue with stripe material not showing

### PR DESCRIPTION
**Pull request by torchesburn**
image

https://github.com/webaverse/app/issues/1803#issuecomment-976158446

CHECKLIST:

- You should see an animated stripe material on top of the ramp

### CODE REVIEW

**Review by avaer — APPROVED** [review]
Code LGTM 👍

**Comment by avaer** [comment]
Has this been verified/can be merged? I'm still seeing this error...

**Comment by torchesburn** [comment]
its been verified.

**Comment by torchesburn** [comment]
can be merged.

**Comment by torchesburn** [comment]
https://github.com/webaverse/app/issues/1803#issuecomment-977006353

**Pull request merged**
